### ISSUE TITLE
application.css.sass?

### ISSUE THREAD

**Issue by jondkinney** [jhilden/jquery-ui-sass-rails#1]
I'm a bit confused how you're supposed to use this using the @import methodology you mention. Can you clarify with a full example?

Does application.css.sass replace application.css entirely? Does it complement it? I would think that they would collide having the same name, but then again I've not ever done anything but the vanilla asset pipeline stuff with the manifest files.

Thanks,
Jon

**Comment by sushil10018** [comment]
Here is a nice explanation of how it can be used better: http://www.mattboldt.com/organizing-css-and-sass-rails/

``` ruby
#application.css
/*
 *= require_self
 *= require main
*/
```

then in the file stylesheets/main.scss

``` ruby
#main.scss
@import "jquery-ui";
@import "font-awesome";
@import "bootstrap-sprockets";
@import "base/bootstrap_variables";
@import "bootstrap";
@import "bootstrap-switch.min";
@import "jquery.datetimepicker";
```
